export const COLOR_SCHEMES = {
  WHITEALPHA: 'whiteAlpha',
  BLACKALPHA: 'blackAlpha',
  GRAY: 'gray',
  RED: 'red',
  ORANGE: 'orange',
  YELLOW: 'yellow',
  GREEN: 'green',
  TEAL: 'teal',
  BLUE: 'blue',
  CYAN: 'cyan',
  PURPLE: 'purple',
  PINK: 'pink',
  LINKEDIN: 'linkedin',
  FACEBOOK: 'facebook',
  MESSENGER: 'messenger',
  WHATSAPP: 'whatsapp',
  TWITTER: 'twitter',
  TELEGRAM: 'telegram'
};
